In [1]:
import numpy as np 
import pandas as pd 

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

Bad value in file WindowsPath('C:/Users/bhard/anaconda3/Lib/site-packages/matplotlib/mpl-data/stylelib/classic.mplstyle'), line 162 ('mathtext.default: normal  # The default font to use for math.'): Key mathtext.default: 'normal' is not a valid value for mathtext.default; supported values are ['rm', 'cal', 'bfit', 'it', 'tt', 'sf', 'bf', 'default', 'bb', 'frak', 'scr', 'regular']

Bad key axes3d.depthshade in file C:\Users\bhard\anaconda3\Lib\site-packages\matplotlib\mpl-data\stylelib\classic.mplstyle, line 225 ('axes3d.depthshade   : False   # depth shade for 3D scatter plots')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.10.0/lib/matplotlib/mpl-data/matplotlibrc
or from the matplotlib source distribution

Bad key axes3d.depthshade_minalpha in file C:\Users\bhard\anaconda3\Lib\site-packages\matplotlib\mpl-data\stylelib\classic.mplstyle, line 226 ('axes3d.depthshade_minalpha : 0.3  # minimum alpha value for depth shading')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.10.0/lib/matplotlib/mpl-data/matplotlibrc
or from the matplotlib source distribution
Bad value in file WindowsPath('C:/Users/bhard/anaconda3/Lib/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle'), line 6 ('hatch.color: edge'): Key hatch.color: 'edge' does not look like a color arg

In [2]:
df = pd.read_csv('train.csv',usecols=['Age','Pclass','SibSp','Parch','Survived'])

In [3]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [4]:
df.dropna(inplace=True)

In [5]:
x= df.iloc[:,1:]
y=df.iloc[:,0]

In [6]:
x.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [7]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

# applying feature construction

In [8]:
x['family_size'] = x['SibSp'] + x['Parch'] + 1

In [9]:
x.head()

   Pclass   Age  SibSp  Parch  family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [11]:
x.drop(columns=['SibSp','Parch'],inplace=True)

In [12]:
x.head()

   Pclass   Age  family_size
0       3  22.0            2
1       1  38.0            2
2       3  26.0            1
3       1  35.0            2
4       3  35.0            1

In [13]:
def myfam(num):
    if num==1 :
        #alone 
        return 0
    elif num >1 and num<= 4:
        # avg family 
        return 1 
    else :
        # large family 
        return 2

In [14]:
myfam(3)

1

In [15]:
x['family_type'] = x['family_size'].apply(myfam)

In [16]:
x.head()

   Pclass   Age  family_size  family_type
0       3  22.0            2            1
1       1  38.0            2            1
2       3  26.0            1            0
3       1  35.0            2            1
4       3  35.0            1            0

In [17]:
x.drop(columns=['family_size'],inplace=True)

In [18]:
x.head()

   Pclass   Age  family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [19]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

In [20]:
x.columns

Index(['Pclass', 'Age', 'family_type'], dtype='object')

In [21]:
z= df.iloc[:,1:]

In [22]:
z['family_size'] = z['SibSp'] + z['Parch'] + 1

In [23]:
z['family_type'] = z['family_size'].apply(myfam)

In [34]:
z.head()

   Pclass   Age  family_size
0       3  22.0            2
1       1  38.0            2
2       3  26.0            1
3       1  35.0            2
4       3  35.0            1

In [ ]:
# i already did z.drop(columns=['family_type'],inplace=True)

In [32]:
np.mean(cross_val_score(LogisticRegression(),z,y,scoring='accuracy',cv=20))

np.float64(0.6919444444444444)

In [30]:
z.head()

   Pclass   Age  family_size  family_type
0       3  22.0            2            1
1       1  38.0            2            1
2       3  26.0            1            0
3       1  35.0            2            1
4       3  35.0            1            0

# feature splitting

In [37]:
df1 = pd.read_csv('train.csv')

In [38]:
df1.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [40]:
df1['title'] = df1['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [43]:
df1[['title','Name']]

     title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [46]:
(df1.groupby('title')['Survived'].mean()).sort_values(ascending=False)

title
the Countess    1.000000
Mlle            1.000000
Sir             1.000000
Ms              1.000000
Lady            1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Col             0.500000
Major           0.500000
Dr              0.428571
Mr              0.156673
Jonkheer        0.000000
Rev             0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64

In [76]:
df1['is_married'] = 0 
df1['title'] = df1['title'].str.strip()
df1['is_married'] = np.where(df1['title']== 'Mrs',1,0 )

In [77]:
df1['is_married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: is_married, Length: 891, dtype: int64