In [1]:
import numpy as np 
import pandas as pd

In [2]:
time = pd.read_csv('messages.csv')
date = pd.read_csv('orders.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info(
    
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [13]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year  date_day
0 2019-12-10        5628       25       3       2019        10
1 2018-08-15        3646       14     157       2018        15
2 2018-10-23        1859       25       1       2018        23
3 2019-08-17        7292       25       1       2019        17
4 2019-01-06        4344       25       3       2019         6

In [14]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_day
0 2019-12-10        5628       25       3       2019        10
1 2018-08-15        3646       14     157       2018        15
2 2018-10-23        1859       25       1       2018        23
3 2019-08-17        7292       25       1       2019        17
4 2019-01-06        4344       25       3       2019         6

In [15]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_day  date_month
0 2019-12-10        5628       25       3       2019        10          12
1 2018-08-15        3646       14     157       2018        15           8
2 2018-10-23        1859       25       1       2018        23          10
3 2019-08-17        7292       25       1       2019        17           8
4 2019-01-06        4344       25       3       2019         6           1

In [16]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,10,12,December
1,2018-08-15,3646,14,157,2018,15,8,August
2,2018-10-23,1859,25,1,2018,23,10,October
3,2019-08-17,7292,25,1,2019,17,8,August
4,2019-01-06,4344,25,3,2019,6,1,January

In [17]:
date['date_day_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_day_name
0,2019-12-10,5628,25,3,2019,10,12,December,Tuesday
1,2018-08-15,3646,14,157,2018,15,8,August,Wednesday
2,2018-10-23,1859,25,1,2018,23,10,October,Tuesday
3,2019-08-17,7292,25,1,2019,17,8,August,Saturday
4,2019-01-06,4344,25,3,2019,6,1,January,Sunday

In [29]:
date['date_day_no'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_day_name,date_week_no,date_is_weekend,date_day_no
0,2019-12-10,5628,25,3,2019,10,12,December,Tuesday,50,0,1
1,2018-08-15,3646,14,157,2018,15,8,August,Wednesday,33,0,2
2,2018-10-23,1859,25,1,2018,23,10,October,Tuesday,43,0,1
3,2019-08-17,7292,25,1,2019,17,8,August,Saturday,33,1,5
4,2019-01-06,4344,25,3,2019,6,1,January,Sunday,1,1,6

In [28]:
date['date_is_weekend'] = np.where(date['date_day_name'].isin(['Saturday','Sunday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_day_name,date_week_no,date_is_weekend,date_day_no
0,2019-12-10,5628,25,3,2019,10,12,December,Tuesday,50,0,1
1,2018-08-15,3646,14,157,2018,15,8,August,Wednesday,33,0,2
2,2018-10-23,1859,25,1,2018,23,10,October,Tuesday,43,0,1
3,2019-08-17,7292,25,1,2019,17,8,August,Saturday,33,1,5
4,2019-01-06,4344,25,3,2019,6,1,January,Sunday,1,1,6

In [27]:
# extract week no 
date['date_week_no'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_day,date_month,date_month_name,date_day_name,date_week_no,date_is_weekend,date_day_no
0,2019-12-10,5628,25,3,2019,10,12,December,Tuesday,50,0,1
1,2018-08-15,3646,14,157,2018,15,8,August,Wednesday,33,0,2
2,2018-10-23,1859,25,1,2018,23,10,October,Tuesday,43,0,1
3,2019-08-17,7292,25,1,2019,17,8,August,Saturday,33,1,5
4,2019-01-06,4344,25,3,2019,6,1,January,Sunday,1,1,6

In [32]:
date = date.drop(columns=['product_id','city_id','orders'])

In [33]:
date['date_quater'] = date['date'].dt.quarter
date.head()

,date,date_year,date_day,date_month,date_month_name,date_day_name,date_week_no,date_is_weekend,date_day_no,date_quater
0,2019-12-10,2019,10,12,December,Tuesday,50,0,1,4
1,2018-08-15,2018,15,8,August,Wednesday,33,0,2,3
2,2018-10-23,2018,23,10,October,Tuesday,43,0,1,4
3,2019-08-17,2019,17,8,August,Saturday,33,1,5,3
4,2019-01-06,2019,6,1,January,Sunday,1,1,6,1

In [34]:
date['semester'] = np.where(date['date_quater'].isin([1,2]),1,2)
date.head()

,date,date_year,date_day,date_month,date_month_name,date_day_name,date_week_no,date_is_weekend,date_day_no,date_quater,semester
0,2019-12-10,2019,10,12,December,Tuesday,50,0,1,4,2
1,2018-08-15,2018,15,8,August,Wednesday,33,0,2,3,2
2,2018-10-23,2018,23,10,October,Tuesday,43,0,1,4,2
3,2019-08-17,2019,17,8,August,Saturday,33,1,5,3,2
4,2019-01-06,2019,6,1,January,Sunday,1,1,6,1,1

In [35]:
import datetime 
today = datetime.datetime.today()

In [36]:
today- date['date']

0     2417 days 23:26:38.700314
1     2899 days 23:26:38.700314
2     2830 days 23:26:38.700314
3     2532 days 23:26:38.700314
4     2755 days 23:26:38.700314
                 ...
995   2845 days 23:26:38.700314
996   2786 days 23:26:38.700314
997   2634 days 23:26:38.700314
998   2699 days 23:26:38.700314
999   2473 days 23:26:38.700314
Name: date, Length: 1000, dtype: timedelta64[ns]

In [39]:
(today- date['date']).dt.days

0      2417
1      2899
2      2830
3      2532
4      2755
       ...
995    2845
996    2786
997    2634
998    2699
999    2473
Name: date, Length: 1000, dtype: int64

In [43]:
np.round((today- date['date']).dt.days / 30.4375,0)

0      79.0
1      95.0
2      93.0
3      83.0
4      91.0
       ...
995    93.0
996    92.0
997    87.0
998    89.0
999    81.0
Name: date, Length: 1000, dtype: float64

# time

In [44]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [45]:
time['date'] = pd.to_datetime(time['date'])

In [46]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [48]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [49]:
time['time'] = time['date'].dt.time

In [51]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00